### ISSUE TITLE
此方案可否兼容 symbols？尝试失败

### ISSUE THREAD

**Issue by EthanYangCX** [rime/rime-terra-pinyin#46]
我在 terra_pinyin.schema.yaml 里面的 `punctuator:` 里加入了 `import_preset: symbols`，也点击了「重新部署」，但还是无法使用 symbols 的模式来输入符号。请问是方案本身不兼容么，还是说我操作错误？

**Comment by EthanYangCX** [comment]
对不起，我是新手，在 shema 里面再加入这个就好了：

```yaml
recognizer:
  patterns:
    punct: "^/([0-9]0?|[A-Za-z]+)$"
```

私心认为这个配置可以设为默认，就像 `luna_pinyin` 和 `cantonese` 等方案一样，不知道有没有别的考虑导致没有设为默认？
